### ISSUE TITLE
Supply Compose With More Permissive Type

### ISSUE THREAD

**Issue by Megamiun** [markhobson/hamcrest-compose#13]
Hello, I was testing some things and found a gap in your library.

My test is for a tree structure. As I was making a test, I found myself with this:

```java

private Matcher<Holder> isExpressionWith(ExpressionType type, Matcher<Holder> left, Matcher<Holder> right) {
       return compose("holder with",
                hasFeature("holderType", it -> it.getHolderType(), equalTo(EXPRESSION)),

                hasFeature("that has", exp -> (ExpressionHolder) exp,
                        hasFeature("expressionType", exp -> exp.getExpressionType(), equalTo(type)),
                        hasFeature("left", exp -> exp.getLeft(), left),
                        hasFeature("right", exp -> exp.getRight(), right)
                )
        );
```

As it can be seem, I made some changes on another class so I could have a compose that receives a vararg of matchers instead of just one, so to avoid a little of chaining. Same with the method hasFeature, that inside calls the hasFeature(featureFunction, compose(featureName, featureMatchers)).

The only problem is that compose, that I think has the idea of working similar to hamcrest allOf, doesn't accept `Matcher<? super T>` as a parameter, but only `Matcher<T>`. Is there any reason to that? Can I submit a PR to that? And possibly for a new method accepting a vararg of items instead of just a list in compose?

**Comment by markhobson** [comment]
Thanks for the feedback. I agree that `compose` should take `Matcher<? super T>` rather than `Matcher<T>`. Let's use this issue for that.

We should raise another issue for the varargs suggestion. It seems reasonable enough for `compose` considering there's already a `List<Matcher<T>>` variant. I'd suggest changing the methods that take a singular `Matcher<T>` to `Matcher<T>...`. I'm not sure that the extra complexity is warranted for adding varargs to `hasFeature` though -- would not wrapping the matchers with a varargs `compose` suffice instead?

**Comment by Megamiun** [comment]
Ok, I'll try to implement those functions, @markhobson.

About the varargs to `hasFeature`, I think that I maybe agree about it being best to leave it out, it was more something personal, but that already gave me some problems(`compose` doesn't match some values because of `TypeSafeDiagnosingMatcher#matches`, that reject any null value, impossibiliting constructs like `compose("nullStringValue", is(nullValue()))`).

**Comment by markhobson** [comment]
Great, thanks @Megamiun! The `nullValue` use-case for `compose` sounds like a bug, could you raise another issue for that please? Perhaps `ConjunctionMatcher` should extend `DiagnosingMatcher` instead of `TypeSafeDiagnosingMatcher` to fix that.
