### ISSUE TITLE
Add varargs support for compose

### ISSUE THREAD

**Issue by Megamiun** [markhobson/hamcrest-compose#14]
As said in issue #13:

> We should raise another issue for the varargs suggestion. It seems reasonable enough for `compose` considering there's already a `List<Matcher<T>>` variant. I'd suggest changing the methods that take a singular `Matcher<T>` to `Matcher<T>...`. 

The idea is to create a varargs variant for the `compose` method.

**Comment by Megamiun** [comment]
Oh, and I hope it is no a problem, but I added a check to see if any item on the list/array is null, I thought it was a good idea as we already validated on the simple versions of `compose` and on `ConjunctionMatcher#and` if the item was null.

And otherwise, the test would fail on assert if we passed a list or array with a null value.

**Comment by markhobson** [comment]
Thanks for the PR @Megamiun! Merged with minor changes.
